using EInvoice.Xsd.Invoice.DocumentReference;
using System;
using System.Diagnostics;
using System.Xml.Serialization;

namespace EInvoice.Xsd.Invoice.Bases {

    [XmlIncludeAttribute(typeof(CodeType1))]
    [XmlIncludeAttribute(typeof(ExtensionReasonCodeType))]
    [XmlIncludeAttribute(typeof(WorkPhaseCodeType))]
    [XmlIncludeAttribute(typeof(WeightingAlgorithmCodeType))]
    [XmlIncludeAttribute(typeof(WeekDayCodeType))]
    [XmlIncludeAttribute(typeof(ValidationResultCodeType))]
    [XmlIncludeAttribute(typeof(UtilityStatementTypeCodeType))]
    [XmlIncludeAttribute(typeof(UrgencyCodeType))]
    [XmlIncludeAttribute(typeof(UNDGCodeType))]
    [XmlIncludeAttribute(typeof(TypeCodeType))]
    [XmlIncludeAttribute(typeof(TransportationStatusTypeCodeType))]
    [XmlIncludeAttribute(typeof(TransportServiceCodeType))]
    [XmlIncludeAttribute(typeof(TransportModeCodeType))]
    [XmlIncludeAttribute(typeof(TransportMeansTypeCodeType))]
    [XmlIncludeAttribute(typeof(TransportHandlingUnitTypeCodeType))]
    [XmlIncludeAttribute(typeof(TransportExecutionStatusCodeType))]
    [XmlIncludeAttribute(typeof(TransportEventTypeCodeType))]
    [XmlIncludeAttribute(typeof(TransportEquipmentTypeCodeType))]
    [XmlIncludeAttribute(typeof(TransportEmergencyCardCodeType))]
    [XmlIncludeAttribute(typeof(TransportAuthorizationCodeType))]
    [XmlIncludeAttribute(typeof(TransitDirectionCodeType))]
    [XmlIncludeAttribute(typeof(TradeServiceCodeType))]
    [XmlIncludeAttribute(typeof(TradeItemPackingLabelingTypeCodeType))]
    [XmlIncludeAttribute(typeof(TrackingDeviceCodeType))]
    [XmlIncludeAttribute(typeof(TimingComplaintCodeType))]
    [XmlIncludeAttribute(typeof(TimeFrequencyCodeType))]
    [XmlIncludeAttribute(typeof(ThresholdValueComparisonCodeType))]
    [XmlIncludeAttribute(typeof(TendererRoleCodeType))]
    [XmlIncludeAttribute(typeof(TendererRequirementTypeCodeType))]
    [XmlIncludeAttribute(typeof(TenderTypeCodeType))]
    [XmlIncludeAttribute(typeof(TenderResultCodeType))]
    [XmlIncludeAttribute(typeof(TenderEnvelopeTypeCodeType))]
    [XmlIncludeAttribute(typeof(TelecommunicationsSupplyTypeCodeType))]
    [XmlIncludeAttribute(typeof(TelecommunicationsServiceCategoryCodeType))]
    [XmlIncludeAttribute(typeof(TelecommunicationsServiceCallCodeType))]
    [XmlIncludeAttribute(typeof(TaxTypeCodeType))]
    [XmlIncludeAttribute(typeof(TaxLevelCodeType))]
    [XmlIncludeAttribute(typeof(TaxExemptionReasonCodeType))]
    [XmlIncludeAttribute(typeof(TaxCurrencyCodeType))]
    [XmlIncludeAttribute(typeof(TariffCodeType))]
    [XmlIncludeAttribute(typeof(TariffClassCodeType))]
    [XmlIncludeAttribute(typeof(TargetCurrencyCodeType))]
    [XmlIncludeAttribute(typeof(SupplyChainActivityTypeCodeType))]
    [XmlIncludeAttribute(typeof(SubstitutionStatusCodeType))]
    [XmlIncludeAttribute(typeof(SubscriberTypeCodeType))]
    [XmlIncludeAttribute(typeof(SubmissionMethodCodeType))]
    [XmlIncludeAttribute(typeof(SubcontractingConditionsCodeType))]
    [XmlIncludeAttribute(typeof(StatusReasonCodeType))]
    [XmlIncludeAttribute(typeof(StatusCodeType))]
    [XmlIncludeAttribute(typeof(StatementTypeCodeType))]
    [XmlIncludeAttribute(typeof(SpecificationTypeCodeType))]
    [XmlIncludeAttribute(typeof(SourceCurrencyCodeType))]
    [XmlIncludeAttribute(typeof(SizeTypeCodeType))]
    [XmlIncludeAttribute(typeof(ShortageActionCodeType))]
    [XmlIncludeAttribute(typeof(ShippingPriorityLevelCodeType))]
    [XmlIncludeAttribute(typeof(ServiceTypeCodeType))]
    [XmlIncludeAttribute(typeof(ServiceInformationPreferenceCodeType))]
    [XmlIncludeAttribute(typeof(SecurityClassificationCodeType))]
    [XmlIncludeAttribute(typeof(SealStatusCodeType))]
    [XmlIncludeAttribute(typeof(SealIssuerTypeCodeType))]
    [XmlIncludeAttribute(typeof(RoleCodeType))]
    [XmlIncludeAttribute(typeof(RevisionStatusCodeType))]
    [XmlIncludeAttribute(typeof(RetailEventStatusCodeType))]
    [XmlIncludeAttribute(typeof(ResponseCodeType))]
    [XmlIncludeAttribute(typeof(ResolutionCodeType))]
    [XmlIncludeAttribute(typeof(ResidenceTypeCodeType))]
    [XmlIncludeAttribute(typeof(RequestedInvoiceCurrencyCodeType))]
    [XmlIncludeAttribute(typeof(ReminderTypeCodeType))]
    [XmlIncludeAttribute(typeof(RejectReasonCodeType))]
    [XmlIncludeAttribute(typeof(RejectActionCodeType))]
    [XmlIncludeAttribute(typeof(ReferenceEventCodeType))]
    [XmlIncludeAttribute(typeof(ReceiptAdviceTypeCodeType))]
    [XmlIncludeAttribute(typeof(QuantityDiscrepancyCodeType))]
    [XmlIncludeAttribute(typeof(QualityControlCodeType))]
    [XmlIncludeAttribute(typeof(PurposeCodeType))]
    [XmlIncludeAttribute(typeof(ProviderTypeCodeType))]
    [XmlIncludeAttribute(typeof(PromotionalEventTypeCodeType))]
    [XmlIncludeAttribute(typeof(ProfileStatusCodeType))]
    [XmlIncludeAttribute(typeof(ProcurementTypeCodeType))]
    [XmlIncludeAttribute(typeof(ProcurementSubTypeCodeType))]
    [XmlIncludeAttribute(typeof(ProcessReasonCodeType))]
    [XmlIncludeAttribute(typeof(ProcedureCodeType))]
    [XmlIncludeAttribute(typeof(PrivacyCodeType))]
    [XmlIncludeAttribute(typeof(PricingCurrencyCodeType))]
    [XmlIncludeAttribute(typeof(PriceTypeCodeType))]
    [XmlIncludeAttribute(typeof(PriceEvaluationCodeType))]
    [XmlIncludeAttribute(typeof(PreviousMeterReadingMethodCodeType))]
    [XmlIncludeAttribute(typeof(PreviousCancellationReasonCodeType))]
    [XmlIncludeAttribute(typeof(PreferenceCriterionCodeType))]
    [XmlIncludeAttribute(typeof(PositionCodeType))]
    [XmlIncludeAttribute(typeof(PerformanceMetricTypeCodeType))]
    [XmlIncludeAttribute(typeof(PaymentPurposeCodeType))]
    [XmlIncludeAttribute(typeof(PaymentMeansCodeType))]
    [XmlIncludeAttribute(typeof(PaymentFrequencyCodeType))]
    [XmlIncludeAttribute(typeof(PaymentCurrencyCodeType))]
    [XmlIncludeAttribute(typeof(PaymentChannelCodeType))]
    [XmlIncludeAttribute(typeof(PaymentAlternativeCurrencyCodeType))]
    [XmlIncludeAttribute(typeof(PartyTypeCodeType))]
    [XmlIncludeAttribute(typeof(PartPresentationCodeType))]
    [XmlIncludeAttribute(typeof(ParentDocumentTypeCodeType))]
    [XmlIncludeAttribute(typeof(PackingCriteriaCodeType))]
    [XmlIncludeAttribute(typeof(PackagingTypeCodeType))]
    [XmlIncludeAttribute(typeof(PackageLevelCodeType))]
    [XmlIncludeAttribute(typeof(PackLevelCodeType))]
    [XmlIncludeAttribute(typeof(OwnerTypeCodeType))]
    [XmlIncludeAttribute(typeof(OrderTypeCodeType))]
    [XmlIncludeAttribute(typeof(OrderResponseCodeType))]
    [XmlIncludeAttribute(typeof(OneTimeChargeTypeCodeType))]
    [XmlIncludeAttribute(typeof(NotificationTypeCodeType))]
    [XmlIncludeAttribute(typeof(NatureCodeType))]
    [XmlIncludeAttribute(typeof(NameCodeType))]
    [XmlIncludeAttribute(typeof(MiscellaneousEventTypeCodeType))]
    [XmlIncludeAttribute(typeof(MimeCodeType))]
    [XmlIncludeAttribute(typeof(MeterReadingTypeCodeType))]
    [XmlIncludeAttribute(typeof(MeterConstantCodeType))]
    [XmlIncludeAttribute(typeof(MedicalFirstAidGuideCodeType))]
    [XmlIncludeAttribute(typeof(MathematicOperatorCodeType))]
    [XmlIncludeAttribute(typeof(MandateTypeCodeType))]
    [XmlIncludeAttribute(typeof(LossRiskResponsibilityCodeType))]
    [XmlIncludeAttribute(typeof(LongitudeDirectionCodeType))]
    [XmlIncludeAttribute(typeof(LocationTypeCodeType))]
    [XmlIncludeAttribute(typeof(LocaleCodeType))]
    [XmlIncludeAttribute(typeof(LineStatusCodeType))]
    [XmlIncludeAttribute(typeof(LifeCycleStatusCodeType))]
    [XmlIncludeAttribute(typeof(LatitudeDirectionCodeType))]
    [XmlIncludeAttribute(typeof(LatestMeterReadingMethodCodeType))]
    [XmlIncludeAttribute(typeof(ItemClassificationCodeType))]
    [XmlIncludeAttribute(typeof(InvoiceTypeCodeType))]
    [XmlIncludeAttribute(typeof(InspectionMethodCodeType))]
    [XmlIncludeAttribute(typeof(InhalationToxicityZoneCodeType))]
    [XmlIncludeAttribute(typeof(IndustryClassificationCodeType))]
    [XmlIncludeAttribute(typeof(ImportanceCodeType))]
    [XmlIncludeAttribute(typeof(IdentificationCodeType))]
    [XmlIncludeAttribute(typeof(HeatingTypeCodeType))]
    [XmlIncludeAttribute(typeof(HazardousRegulationCodeType))]
    [XmlIncludeAttribute(typeof(HazardousCategoryCodeType))]
    [XmlIncludeAttribute(typeof(HandlingCodeType))]
    [XmlIncludeAttribute(typeof(GuaranteeTypeCodeType))]
    [XmlIncludeAttribute(typeof(GenderCodeType))]
    [XmlIncludeAttribute(typeof(FundingProgramCodeType))]
    [XmlIncludeAttribute(typeof(FullnessIndicationCodeType))]
    [XmlIncludeAttribute(typeof(FreightRateClassCodeType))]
    [XmlIncludeAttribute(typeof(FormatCodeType))]
    [XmlIncludeAttribute(typeof(ForecastTypeCodeType))]
    [XmlIncludeAttribute(typeof(ForecastPurposeCodeType))]
    [XmlIncludeAttribute(typeof(FinancingInstrumentCodeType))]
    [XmlIncludeAttribute(typeof(FeatureTacticTypeCodeType))]
    [XmlIncludeAttribute(typeof(ExpressionCodeType))]
    [XmlIncludeAttribute(typeof(ExpenseCodeType))]
    [XmlIncludeAttribute(typeof(ExemptionReasonCodeType))]
    [XmlIncludeAttribute(typeof(ExecutionRequirementCodeType))]
    [XmlIncludeAttribute(typeof(ExceptionStatusCodeType))]
    [XmlIncludeAttribute(typeof(ExceptionResolutionCodeType))]
    [XmlIncludeAttribute(typeof(EvidenceTypeCodeType))]
    [XmlIncludeAttribute(typeof(EvaluationCriterionTypeCodeType))]
    [XmlIncludeAttribute(typeof(EnvironmentalEmissionTypeCodeType))]
    [XmlIncludeAttribute(typeof(EncodingCodeType))]
    [XmlIncludeAttribute(typeof(EmergencyProceduresCodeType))]
    [XmlIncludeAttribute(typeof(DutyCodeType))]
    [XmlIncludeAttribute(typeof(DocumentTypeCodeType))]
    [XmlIncludeAttribute(typeof(DocumentStatusReasonCodeType))]
    [XmlIncludeAttribute(typeof(DocumentStatusCodeType))]
    [XmlIncludeAttribute(typeof(DocumentCurrencyCodeType))]
    [XmlIncludeAttribute(typeof(DispositionCodeType))]
    [XmlIncludeAttribute(typeof(DisplayTacticTypeCodeType))]
    [XmlIncludeAttribute(typeof(DirectionCodeType))]
    [XmlIncludeAttribute(typeof(DespatchAdviceTypeCodeType))]
    [XmlIncludeAttribute(typeof(DescriptionCodeType))]
    [XmlIncludeAttribute(typeof(DeclarationTypeCodeType))]
    [XmlIncludeAttribute(typeof(DataSourceCodeType))]
    [XmlIncludeAttribute(typeof(CustomsStatusCodeType))]
    [XmlIncludeAttribute(typeof(CurrentChargeTypeCodeType))]
    [XmlIncludeAttribute(typeof(CurrencyCodeType))]
    [XmlIncludeAttribute(typeof(CreditNoteTypeCodeType))]
    [XmlIncludeAttribute(typeof(CountrySubentityCodeType))]
    [XmlIncludeAttribute(typeof(CorrectionTypeCodeType))]
    [XmlIncludeAttribute(typeof(CorporateRegistrationTypeCodeType))]
    [XmlIncludeAttribute(typeof(CoordinateSystemCodeType))]
    [XmlIncludeAttribute(typeof(ContractingSystemCodeType))]
    [XmlIncludeAttribute(typeof(ContractTypeCodeType))]
    [XmlIncludeAttribute(typeof(ConsumptionTypeCodeType))]
    [XmlIncludeAttribute(typeof(ConsumptionLevelCodeType))]
    [XmlIncludeAttribute(typeof(ConsumersEnergyLevelCodeType))]
    [XmlIncludeAttribute(typeof(ConsumerIncentiveTacticTypeCodeType))]
    [XmlIncludeAttribute(typeof(ConstitutionCodeType))]
    [XmlIncludeAttribute(typeof(ConditionCodeType))]
    [XmlIncludeAttribute(typeof(ComparisonDataSourceCodeType))]
    [XmlIncludeAttribute(typeof(ComparisonDataCodeType))]
    [XmlIncludeAttribute(typeof(CompanyLiquidationStatusCodeType))]
    [XmlIncludeAttribute(typeof(CompanyLegalFormCodeType))]
    [XmlIncludeAttribute(typeof(CommodityCodeType))]
    [XmlIncludeAttribute(typeof(CollaborationPriorityCodeType))]
    [XmlIncludeAttribute(typeof(CharacterSetCodeType))]
    [XmlIncludeAttribute(typeof(ChannelCodeType))]
    [XmlIncludeAttribute(typeof(CertificateTypeCodeType))]
    [XmlIncludeAttribute(typeof(CargoTypeCodeType))]
    [XmlIncludeAttribute(typeof(CardTypeCodeType))]
    [XmlIncludeAttribute(typeof(CardChipCodeType))]
    [XmlIncludeAttribute(typeof(CapabilityTypeCodeType))]
    [XmlIncludeAttribute(typeof(CalculationMethodCodeType))]
    [XmlIncludeAttribute(typeof(CalculationExpressionCodeType))]
    [XmlIncludeAttribute(typeof(AwardingMethodTypeCodeType))]
    [XmlIncludeAttribute(typeof(AwardingCriterionTypeCodeType))]
    [XmlIncludeAttribute(typeof(AvailabilityStatusCodeType))]
    [XmlIncludeAttribute(typeof(ApplicationStatusCodeType))]
    [XmlIncludeAttribute(typeof(AllowanceChargeReasonCodeType))]
    [XmlIncludeAttribute(typeof(AdmissionCodeType))]
    [XmlIncludeAttribute(typeof(AdjustmentReasonCodeType))]
    [XmlIncludeAttribute(typeof(AddressTypeCodeType))]
    [XmlIncludeAttribute(typeof(AddressFormatCodeType))]
    [XmlIncludeAttribute(typeof(ActivityTypeCodeType))]
    [XmlIncludeAttribute(typeof(ActionCodeType))]
    [XmlIncludeAttribute(typeof(AccountingCostCodeType))]
    [XmlIncludeAttribute(typeof(AccountTypeCodeType))]
    [XmlIncludeAttribute(typeof(AccountFormatCodeType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2")]
    public partial class CodeType {        
        [XmlAttribute(DataType = "normalizedString")]
        public string listID { get; set; }

        [XmlAttribute(DataType = "normalizedString")]
        public string listAgencyID { get; set; }

        [XmlAttribute]
        public string listAgencyName { get; set; }

        [XmlAttribute]
        public string listName { get; set; }

        [XmlAttribute(DataType = "normalizedString")]
        public string listVersionID { get; set; }

        [XmlAttribute]
        public string name { get; set; }

        [XmlAttribute(DataType = "language")]
        public string languageID { get; set; }

        [XmlAttribute(DataType = "anyURI")]
        public string listURI { get; set; }

        [XmlAttribute(DataType = "anyURI")]
        public string listSchemeURI { get; set; }

        [XmlTextAttribute(DataType = "normalizedString")]
        public string Value { get; set; }
    }
}
