using System;
using System.Diagnostics;
using System.Xml.Serialization;

namespace EInvoice.Xsd.Invoice.Bases {
    [XmlIncludeAttribute(typeof(ValidityStartDateType))]
    [XmlIncludeAttribute(typeof(ValidationDateType))]
    [XmlIncludeAttribute(typeof(TaxPointDateType))]
    [XmlIncludeAttribute(typeof(SubmissionDueDateType))]
    [XmlIncludeAttribute(typeof(SubmissionDateType))]
    [XmlIncludeAttribute(typeof(StartDateType))]
    [XmlIncludeAttribute(typeof(SourceForecastIssueDateType))]
    [XmlIncludeAttribute(typeof(RevisionDateType))]
    [XmlIncludeAttribute(typeof(ResponseDateType))]
    [XmlIncludeAttribute(typeof(ResolutionDateType))]
    [XmlIncludeAttribute(typeof(RequiredDeliveryDateType))]
    [XmlIncludeAttribute(typeof(RequestedPublicationDateType))]
    [XmlIncludeAttribute(typeof(RequestedDespatchDateType))]
    [XmlIncludeAttribute(typeof(RequestedDeliveryDateType))]
    [XmlIncludeAttribute(typeof(RegistrationExpirationDateType))]
    [XmlIncludeAttribute(typeof(RegistrationDateType))]
    [XmlIncludeAttribute(typeof(RegisteredDateType))]
    [XmlIncludeAttribute(typeof(ReferenceDateType))]
    [XmlIncludeAttribute(typeof(ReceivedDateType))]
    [XmlIncludeAttribute(typeof(PreviousMeterReadingDateType))]
    [XmlIncludeAttribute(typeof(PlannedDateType))]
    [XmlIncludeAttribute(typeof(PaymentDueDateType))]
    [XmlIncludeAttribute(typeof(PaidDateType))]
    [XmlIncludeAttribute(typeof(OccurrenceDateType))]
    [XmlIncludeAttribute(typeof(NominationDateType))]
    [XmlIncludeAttribute(typeof(ManufactureDateType))]
    [XmlIncludeAttribute(typeof(LatestSecurityClearanceDateType))]
    [XmlIncludeAttribute(typeof(LatestProposalAcceptanceDateType))]
    [XmlIncludeAttribute(typeof(LatestPickupDateType))]
    [XmlIncludeAttribute(typeof(LatestMeterReadingDateType))]
    [XmlIncludeAttribute(typeof(LatestDeliveryDateType))]
    [XmlIncludeAttribute(typeof(LastRevisionDateType))]
    [XmlIncludeAttribute(typeof(IssueDateType))]
    [XmlIncludeAttribute(typeof(InstallmentDueDateType))]
    [XmlIncludeAttribute(typeof(GuaranteedDespatchDateType))]
    [XmlIncludeAttribute(typeof(FirstShipmentAvailibilityDateType))]
    [XmlIncludeAttribute(typeof(ExpiryDateType))]
    [XmlIncludeAttribute(typeof(EstimatedDespatchDateType))]
    [XmlIncludeAttribute(typeof(EstimatedDeliveryDateType))]
    [XmlIncludeAttribute(typeof(EndDateType))]
    [XmlIncludeAttribute(typeof(EffectiveDateType))]
    [XmlIncludeAttribute(typeof(EarliestPickupDateType))]
    [XmlIncludeAttribute(typeof(DueDateType))]
    [XmlIncludeAttribute(typeof(DateType1))]
    [XmlIncludeAttribute(typeof(ComparisonForecastIssueDateType))]
    [XmlIncludeAttribute(typeof(CallDateType))]
    [XmlIncludeAttribute(typeof(BirthDateType))]
    [XmlIncludeAttribute(typeof(BestBeforeDateType))]
    [XmlIncludeAttribute(typeof(AwardDateType))]
    [XmlIncludeAttribute(typeof(AvailabilityDateType))]
    [XmlIncludeAttribute(typeof(ApprovalDateType))]
    [XmlIncludeAttribute(typeof(ActualPickupDateType))]
    [XmlIncludeAttribute(typeof(ActualDespatchDateType))]
    [XmlIncludeAttribute(typeof(ActualDeliveryDateType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
    public partial class DateType {

        [XmlTextAttribute(DataType = "date")]
        public System.DateTime Value { get; set; }
    }
}
