using System;
using System.Diagnostics;
using System.Xml.Serialization;

namespace EInvoice.Xsd.Invoice.Bases {
    [XmlIncludeAttribute(typeof(VariantConstraintIndicatorType))]
    [XmlIncludeAttribute(typeof(UnknownPriceIndicatorType))]
    [XmlIncludeAttribute(typeof(ToOrderIndicatorType))]
    [XmlIncludeAttribute(typeof(ThirdPartyPayerIndicatorType))]
    [XmlIncludeAttribute(typeof(TaxIncludedIndicatorType))]
    [XmlIncludeAttribute(typeof(TaxEvidenceIndicatorType))]
    [XmlIncludeAttribute(typeof(StatusAvailableIndicatorType))]
    [XmlIncludeAttribute(typeof(SplitConsignmentIndicatorType))]
    [XmlIncludeAttribute(typeof(SpecialSecurityIndicatorType))]
    [XmlIncludeAttribute(typeof(SoleProprietorshipIndicatorType))]
    [XmlIncludeAttribute(typeof(ReturnableMaterialIndicatorType))]
    [XmlIncludeAttribute(typeof(ReturnabilityIndicatorType))]
    [XmlIncludeAttribute(typeof(RequiredCurriculaIndicatorType))]
    [XmlIncludeAttribute(typeof(RefrigerationOnIndicatorType))]
    [XmlIncludeAttribute(typeof(RefrigeratedIndicatorType))]
    [XmlIncludeAttribute(typeof(PublishAwardIndicatorType))]
    [XmlIncludeAttribute(typeof(PrizeIndicatorType))]
    [XmlIncludeAttribute(typeof(PricingUpdateRequestIndicatorType))]
    [XmlIncludeAttribute(typeof(PrepaidIndicatorType))]
    [XmlIncludeAttribute(typeof(PreCarriageIndicatorType))]
    [XmlIncludeAttribute(typeof(PowerIndicatorType))]
    [XmlIncludeAttribute(typeof(PartialDeliveryIndicatorType))]
    [XmlIncludeAttribute(typeof(OtherConditionsIndicatorType))]
    [XmlIncludeAttribute(typeof(OrderableIndicatorType))]
    [XmlIncludeAttribute(typeof(OptionalLineItemIndicatorType))]
    [XmlIncludeAttribute(typeof(OnCarriageIndicatorType))]
    [XmlIncludeAttribute(typeof(MarkCareIndicatorType))]
    [XmlIncludeAttribute(typeof(MarkAttentionIndicatorType))]
    [XmlIncludeAttribute(typeof(LivestockIndicatorType))]
    [XmlIncludeAttribute(typeof(LegalStatusIndicatorType))]
    [XmlIncludeAttribute(typeof(ItemUpdateRequestIndicatorType))]
    [XmlIncludeAttribute(typeof(IndicationIndicatorType))]
    [XmlIncludeAttribute(typeof(HumanFoodIndicatorType))]
    [XmlIncludeAttribute(typeof(HumanFoodApprovedIndicatorType))]
    [XmlIncludeAttribute(typeof(HazardousRiskIndicatorType))]
    [XmlIncludeAttribute(typeof(GovernmentAgreementConstraintIndicatorType))]
    [XmlIncludeAttribute(typeof(GeneralCargoIndicatorType))]
    [XmlIncludeAttribute(typeof(FullyPaidSharesIndicatorType))]
    [XmlIncludeAttribute(typeof(FrozenDocumentIndicatorType))]
    [XmlIncludeAttribute(typeof(FreeOfChargeIndicatorType))]
    [XmlIncludeAttribute(typeof(FollowupContractIndicatorType))]
    [XmlIncludeAttribute(typeof(DangerousGoodsApprovedIndicatorType))]
    [XmlIncludeAttribute(typeof(CustomsImportClassifiedIndicatorType))]
    [XmlIncludeAttribute(typeof(CopyIndicatorType))]
    [XmlIncludeAttribute(typeof(ContainerizedIndicatorType))]
    [XmlIncludeAttribute(typeof(ConsolidatableIndicatorType))]
    [XmlIncludeAttribute(typeof(CompletionIndicatorType))]
    [XmlIncludeAttribute(typeof(ChargeIndicatorType))]
    [XmlIncludeAttribute(typeof(CatalogueIndicatorType))]
    [XmlIncludeAttribute(typeof(CandidateReductionConstraintIndicatorType))]
    [XmlIncludeAttribute(typeof(BulkCargoIndicatorType))]
    [XmlIncludeAttribute(typeof(BindingOnBuyerIndicatorType))]
    [XmlIncludeAttribute(typeof(BasedOnConsensusIndicatorType))]
    [XmlIncludeAttribute(typeof(BalanceBroughtForwardIndicatorType))]
    [XmlIncludeAttribute(typeof(BackOrderAllowedIndicatorType))]
    [XmlIncludeAttribute(typeof(AuctionConstraintIndicatorType))]
    [XmlIncludeAttribute(typeof(AnimalFoodIndicatorType))]
    [XmlIncludeAttribute(typeof(AnimalFoodApprovedIndicatorType))]
    [XmlIncludeAttribute(typeof(AdValoremIndicatorType))]
    [XmlIncludeAttribute(typeof(AcceptedIndicatorType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [Serializable]
    [DebuggerStepThrough]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2")]
    public partial class IndicatorType {        
        [XmlTextAttribute]
        public bool Value { get; set; }
    }
}